-- Generated by Oracle SQL Developer Data Modeler 21.1.0.092.1221
--   at:        2022-01-16 12:46:29 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE aud_transaction_data 
    ( 
     id            NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 CACHE 10 ) 
         CONSTRAINT NNC_trx_id NOT NULL , 
     trx_id        NUMBER  NOT NULL , 
     column_name   VARCHAR2 (128) , 
     old_value     CLOB , 
     new_value     CLOB , 
     old_num_value NUMBER , 
     new_num_value NUMBER 
    ) 
;

ALTER TABLE aud_transaction_data 
    ADD CONSTRAINT aud_transaction_data_PK PRIMARY KEY ( id ) ;

CREATE TABLE aud_transactions 
    ( 
     id                NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 CACHE 10 )  NOT NULL , 
     tstamp            TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     table_name        VARCHAR2 (128)  NOT NULL , 
     table_key         VARCHAR2 (255)  NOT NULL , 
     dml               CHAR (1)  NOT NULL , 
     client_identifier VARCHAR2 (64) 
    ) 
;

COMMENT ON COLUMN aud_transactions.table_key IS 'Primary key of the related table' 
;

COMMENT ON COLUMN aud_transactions.client_identifier IS 'Value returned by sys_context(''userenv'',''client_identifier'');' 
;

ALTER TABLE aud_transactions 
    ADD CONSTRAINT aud_transactions_PK PRIMARY KEY ( id ) ;

ALTER TABLE aud_transaction_data 
    ADD CONSTRAINT aud_transaction_data_aud_transactions_FK FOREIGN KEY 
    ( 
     trx_id
    ) 
    REFERENCES aud_transactions 
    ( 
     id
    ) 
;
